### PR TITLE
Normalize eol

### PR DESCRIPTION
**Pull request by tboegi**
Normalize the eols: Files should typically have LF in the repo,
or, when checkout out under Windows, CRLF.

Normalize all files:
 - Create .gitattributes (*)
 - rm .git/index
 - git add .
 - git commit

(*)
I'm not sure if the file
motorApp/AerotechSrc/doCommand.ab
has CRLF because the motor controller needs it, or if we could live
with LF.

To be on the safe side, create
motorApp/AerotechSrc/.gitattributes
and mark
motorApp/AerotechSrc/doCommand.ab
as -text, which means that Git will not do any eol conversion at checkout
or commit.

### CODE REVIEW

**Comment by MarkRivers** [comment]
Hi Torsten,
I think this repository is only for testing, the official motor repository is still Subversion at the APS. My understanding is that when motor and the rest of the synApps modules are moved to github they will be put in the epics-modules project, not the BCDA-APS project.

**Comment by prjemian** [comment]
That's right.  We need good cases to test this process.  Torsten's commits
and PR provide that.  The BCDA sandbox is a good place for it.

Tim Mooney and I agreed that synApps modules will be moved once they are
tagged GIT.  That's better than moving some code in between releases.

Pete

Pete

**Comment by tboegi** [comment]
Thanks for comments - I am aware that this is a playground, and we need to get used to the tools.
So the PR can be applied to the playground as an exercise, that's the intention.

Beside that, either the eol's get fixed before moving to Git, or I will re-submit a PR with the same
content on the epics-modules/motor (whatever comes first)

Does anybody know if
motorApp/AerotechSrc/doCommand.ab
should have CRLF or is LF ok as well ?

**Comment by prjemian** [comment]
That will be review on our end.

**Comment by timmmooney** [comment]
doCommand.ab is a Windows file, so it's going to have CRLF unless a dedicated, ongoing effort is made to change CRLF to LF as it is found.

Tim Mooney (mooney@aps.anl.gov) (630)252-5417
Beamline Controls Group (www.aps.anl.gov)
Advanced Photon Source, Argonne National Lab

________________________________

**Comment by MarkRivers** [comment]
I do a lot of mixed editing on Windows and Linux.  For example, I always clean up .html files with Visual Studio, because it has a nice formatter.  It’s pretty easy to tell when you need to run dos2unix on the files.  Just before you do a commit you do “git diff” on the file, which one should always do anyway.  If every line shows up as changed then you know you have a line ending problem and you run dos2unix on the file.

**Comment by tboegi** [comment]
For those who are not familar with all the little details of git:
Git has a build-in dos2unix when files are commited.
It needs to be activated by a .gitattributes file when you e.g. want to commit
from Git under cygwin.
Other use cases may be shared network folder. Files are edited by a Windows machine,
and commited from Git under Linux.

There a other use cases as well, and there are good reasons to avoid text files with CRLF
 in the repo.
I have tested it on the motor module, and created a pull request for the conversions:
https://github.com/BCDA-APS/conversions/pull/1

 
These very pull request can be used for training

**Comment by tboegi** [comment]
For those who are not familar with all the little details of git:
Git has a build-in dos2unix when files are commited.
It needs to be activated by a .gitattributes file when you e.g. want to commit
from Git under cygwin.
Other use cases may be shared network folder. Files are edited by a Windows machine,
and commited from Git under Linux.

There is a unix2dos conversion on checkout as well, it is activated by either setting
core.autocrlf = true (this is the default under Windws) or core.eol clrf

There a other use cases as well, and there are good reasons to avoid text files with CRLF
in the repo.
I have tested it on the motor module, and created a pull request for the conversions:
BCDA-APS/conversions#1

These very pull request can be used for training

**Comment by rsluiter** [comment]
I assume that the source code changes are all EOL changes and therefore superfluous after the .gitattributes change.

**Comment by MarkRivers** [comment]
You can test to see if the changes are just EOL by using “git diff –w –b”.  If only the EOL changed then it will show the files as identical.

Here is an example, using unix2dos to change the EOL, and then using “git diff” with and without “-w –b” to see the differences.

corvette:~/devel/asyn/documentation>git status .
# On branch master
nothing to commit (working directory clean)

corvette:~/devel/asyn/documentation>unix2dos  RELEASE_NOTES.html
unix2dos: converting file RELEASE_NOTES.html to DOS format ...

corvette:~/devel/asyn/documentation>git diff RELEASE_NOTES.html
diff --git a/documentation/RELEASE_NOTES.html b/documentation/RELEASE_NOTES.html
index 79fb18f..76d7356 100755
--- a/documentation/RELEASE_NOTES.html
+++ b/documentation/RELEASE_NOTES.html
@@ -1,2146 +1,2146 @@
-<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
-<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
-<head>
-  <title>asynDriver: Asynchronous Driver Support - Release Notes</title>
-  <meta content="text/html; charset=ISO-8859-1" http-equiv="Content-Type" />
…

corvette:~/devel/asyn/documentation>git diff -w -b RELEASE_NOTES.html
corvette:~/devel/asyn/documentation>

**Pull request merged**
