### PR TITLE
devMotorAsyn: Send MRES to the driver

### PR DESCRIPTION
**Pull request by tboegi**
Send the motor resolution to the controller.
MRES in the motor record, setDoubleParam(motorResolution_)
in asynMotorAxis.

This is usefull when the motion controller controller always communicates
in engineering units, even for a stepper motor.
Using EGU=mm and MRES=1.0 will only allow to get a readback of the motor
position in mm-steps.

Now it is possible to set MRES=0.001 and get a resolution in micro-meter

### CODE REVIEW

**Comment by tboegi** [comment]
Please don't merge yet, I'll send a better version

**Comment by kmpeters** [comment]
Why does the controller need to know what the MRES of the motor record is?  

The EGU in of the motor record is intended to be user-configurable, which necessarily involves changing the MRES.  Device support receives positions in raw units from the motor record and it is the driver's responsibility to convert these raw units back to whatever engineering unit is used by the controller.  Drivers that operate in engineering units usually have arguments that specify the number of steps per unit for each axis.

If the driver gets the resolution of each axis from the MRES, then the MRES must never be changed, which forces users to work in whatever the current unit used by the controller is.

**Comment by MarkRivers** [comment]
Sometimes the driver really does need to know the values of MRES, OFF, and DIR.  An example is doing ProfileMoves (i.e. trajectory scans with the new Model 3 API) on the Newport XPS.  Those moves are defined by the user in the EPICS coordinate system, but must be executed in the XPS engineering unit coordinate system.  The motor record is not involved in such moves, so it cannot do the EPICS unit to “step” conversion.

I agree with your point that drivers need to handle the fact that MRES can change dynamically.  That is why I removed almost identical code from devMotorAsyn that Torsten is proposing replacing (look at my commented out code in his pull request).  Here is my commented out code in devMotorAsyn.c:
    /* Send the motor resolution to the driver.  This should be done in the record
     * in the future ? */
/*  DON'T DO THIS FOR NOW.  THE NUMBER CAN COME TOO LATE TO BE OF USE TO THE DRIVER
    resolution = pmr->mres;
    pasynUser->reason = pPvt->driverReasons[motorResolution];
    pPvt->pasynFloat64->write(pPvt->asynFloat64Pvt, pasynUser,
                  resolution);
*/

My solution was to add records like the following to  asyn_motor.db:

# Motor resolution for this axis
record(ao,"$(P)$(M)Resolution") {
    field(DESC, "$(M) resolution")
    field(DOL,  "$(P)$(M).MRES CP MS")
    field(OMSL, "closed_loop")
    field(DTYP, "asynFloat64")
    field(OUT,  "@asyn($(PORT),$(ADDR))MOTOR_REC_RESOLUTION")
    field(PREC, "$(PREC)")
}

So this record processes whenever the MRES field changes.  It sends the new value to the driver via an ao record.  There are similar records for the Direction and Offset.  I think this is a better solution than this pull request, and it is already implemented.

**Comment by tboegi** [comment]
Thanks for the explanation and the help to get it working
I would like to postpone the discussion

**Comment by prjemian** [comment]
This pull request has been made in the BCDA sandbox repository: BCDA-APS/motor.

All future development of the motor record will proceed in https://github.com/epics-modules/motor
Please resubmit your changes in that repository.

To allow time for changes to be moved, this repository will be deleted from GitHub on 2015-11-20 (or earlier if all PRs here have been removed).

**Comment by tboegi** [comment]
Pull request can be discarded (La

**Comment by tboegi** [comment]
Pull request can be discared (latest motor record allows to send MRES to the driver using this; 
# Motor resolution for this axis
+record(ao,"$(P)$(M)Resolution")

**Pull request closed without merging**
